blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Wiki
    url: https://wiki.aelysium.group/rusty-connector/
    about: RustyConnector Wiki
  - name: ğŸ’â€â™€ï¸ Help & support on Discord
    url: https://join.aelysium.group
    about: Welcome to our discord community